### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by ibrahimnasson** [znuh/frivpn#2]
is this frivpn compatible with the original OPENVPN SERVER

**Comment by znuh** [comment]
it works with the original openvpn server, but the server needs to be configured in the following way:
- proto TCP instead of UDP
- server cert but no client cert
- client username+password auth
- tls-auth enabled
- comp-lzo
- cipher AES-256-CBC

other options aren't implemented so far

**Comment by ibrahimnasson** [comment]
Thanks alot for the reply,would you mind adding some simple examples/tests
on linking the library to a program..that would be more helpful. .

Thanks in advance,
